/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

/// CommercieleVestigingLinks : URI naar API Vestigingsprofiel voor het huidige vestigingsnummer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommercieleVestigingLinks {
    #[serde(rename = "vestigingsprofiel")]
    pub vestigingsprofiel: Box<models::Link>,
}

impl CommercieleVestigingLinks {
    /// URI naar API Vestigingsprofiel voor het huidige vestigingsnummer
    pub fn new(vestigingsprofiel: models::Link) -> CommercieleVestigingLinks {
        CommercieleVestigingLinks {
            vestigingsprofiel: Box::new(vestigingsprofiel),
        }
    }
}
