/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

/// CommercieleVestiging : Alle namen waaronder een vestiging handelt (op volgorde van registratie)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommercieleVestiging {
    /// Uniek nummer dat bestaat uit 12 cijfers
    #[serde(rename = "vestigingsnummer")]
    pub vestigingsnummer: String,
    /// De eerste handelsnaam van de Vestiging
    #[serde(rename = "eersteHandelsnaam", skip_serializing_if = "Option::is_none")]
    pub eerste_handelsnaam: Option<String>,
    /// Alle namen waaronder een onderneming of vestiging handelt
    #[serde(rename = "handelsnamen", skip_serializing_if = "Option::is_none")]
    pub handelsnamen: Option<Vec<models::Handelsnaam>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::CommercieleVestigingLinks>>,
}

impl CommercieleVestiging {
    /// Alle namen waaronder een vestiging handelt (op volgorde van registratie)
    pub fn new(vestigingsnummer: String) -> CommercieleVestiging {
        CommercieleVestiging {
            vestigingsnummer,
            eerste_handelsnaam: None,
            handelsnamen: None,
            links: None,
        }
    }
}
