/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "fout", skip_serializing_if = "Option::is_none")]
    pub fout: Option<Vec<models::Fout>>,
}

impl Error {
    pub fn new() -> Error {
        Error { fout: None }
    }
}
