/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fout {
    /// Foutcode
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Omschrijving van de foutmelding
    #[serde(rename = "omschrijving", skip_serializing_if = "Option::is_none")]
    pub omschrijving: Option<String>,
}

impl Fout {
    pub fn new() -> Fout {
        Fout {
            code: None,
            omschrijving: None,
        }
    }
}
