/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

/// Handelsnaam : Een handelsnaam is een naam waaronder een vestiging van een onderneming handelt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Handelsnaam {
    /// De handelsnaam van de vestiging
    #[serde(rename = "naam", skip_serializing_if = "Option::is_none")]
    pub naam: Option<String>,
    /// Het volgorde nummer van een handelsnaam
    #[serde(rename = "volgorde", skip_serializing_if = "Option::is_none")]
    pub volgorde: Option<i32>,
}

impl Handelsnaam {
    /// Een handelsnaam is een naam waaronder een vestiging van een onderneming handelt.
    pub fn new() -> Handelsnaam {
        Handelsnaam {
            naam: None,
            volgorde: None,
        }
    }
}
