/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Link {
    #[serde(rename = "rel", skip_serializing_if = "Option::is_none")]
    pub rel: Option<String>,
    #[serde(rename = "href")]
    pub href: String,
    /// Omschrijving van de link
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl Link {
    pub fn new(href: String) -> Link {
        Link {
            rel: None,
            href,
            title: None,
        }
    }
}
