/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Naamgeving {
    /// Nederlands Kamer van Koophandel nummer
    #[serde(rename = "kvkNummer")]
    pub kvk_nummer: String,
    /// RSIN (Rechtspersonen en Samenwerkingsverbanden Informatienummer)  Het RSIN kan voorloopnullen bevatten
    #[serde(rename = "rsin", skip_serializing_if = "Option::is_none")]
    pub rsin: Option<String>,
    /// De naam van de rechtspersoon die opgenomen is in de oprichtingsakte
    #[serde(rename = "statutaireNaam", skip_serializing_if = "Option::is_none")]
    pub statutaire_naam: Option<String>,
    /// Naam of eerste handelsnaam van de inschrijving
    #[serde(rename = "naam", skip_serializing_if = "Option::is_none")]
    pub naam: Option<String>,
    /// Een andere naam waaronder de vereniging, stichtingen en vereniging van eigenaars ook bekend is
    #[serde(rename = "ookGenoemd", skip_serializing_if = "Option::is_none")]
    pub ook_genoemd: Option<String>,
    /// In het handelsregister hebben we voor verschillende dossiers niet de exacte datums kunnen vastleggen. We volgen hier de Handels Register datum vastlegging voor. Hierdoor kan bij een onbekend deel van een datum nullen bevatten. Bij een volledig bekende datum is het formaat YYYYMMDD ( Jaar maand dag), waarbij alleen cijfers zijn toegestaan, inclusief de 0 voor onbekende delen van de datum.  __Mogelijke formaten van waarden__  | Type            | Formaat   | | --------------- | --------- | | Volledige datum | 20150622  | | Dag onbekend    | 20150600  | | Maand onbekend  | 20150012  | | Datum onbekend  | 00000000  |
    #[serde(rename = "startdatum", skip_serializing_if = "Option::is_none")]
    pub startdatum: Option<String>,
    /// In het handelsregister hebben we voor verschillende dossiers niet de exacte datums kunnen vastleggen. We volgen hier de Handels Register datum vastlegging voor. Hierdoor kan bij een onbekend deel van een datum nullen bevatten. Bij een volledig bekende datum is het formaat YYYYMMDD ( Jaar maand dag), waarbij alleen cijfers zijn toegestaan, inclusief de 0 voor onbekende delen van de datum.  __Mogelijke formaten van waarden__  | Type            | Formaat   | | --------------- | --------- | | Volledige datum | 20150622  | | Dag onbekend    | 20150600  | | Maand onbekend  | 20150012  | | Datum onbekend  | 00000000  |
    #[serde(rename = "einddatum", skip_serializing_if = "Option::is_none")]
    pub einddatum: Option<String>,
    /// Lijst van vestigingen
    #[serde(rename = "vestigingen", skip_serializing_if = "Option::is_none")]
    pub vestigingen: Option<Vec<models::Vestiging>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::NaamgevingLinks>>,
}

impl Naamgeving {
    pub fn new(kvk_nummer: String) -> Naamgeving {
        Naamgeving {
            kvk_nummer,
            rsin: None,
            statutaire_naam: None,
            naam: None,
            ook_genoemd: None,
            startdatum: None,
            einddatum: None,
            vestigingen: None,
            links: None,
        }
    }
}
