/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

/// NaamgevingLinks : URI naar API Basisprofiel voor het huidige kvknummer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NaamgevingLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::Link>,
    #[serde(rename = "basisprofiel")]
    pub basisprofiel: Box<models::Link>,
}

impl NaamgevingLinks {
    /// URI naar API Basisprofiel voor het huidige kvknummer
    pub fn new(param_self: models::Link, basisprofiel: models::Link) -> NaamgevingLinks {
        NaamgevingLinks {
            param_self: Box::new(param_self),
            basisprofiel: Box::new(basisprofiel),
        }
    }
}
