/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

/// NietCommercieleVestiging : De naam waaronder een niet commerciele vestiging bekend is
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NietCommercieleVestiging {
    /// Uniek nummer dat bestaat uit 12 cijfers
    #[serde(rename = "vestigingsnummer")]
    pub vestigingsnummer: String,
    /// De naam van de Vestiging
    #[serde(rename = "naam", skip_serializing_if = "Option::is_none")]
    pub naam: Option<String>,
    /// Een andere naam waaronder de vereniging, stichtingen en vereniging van eigenaars ook bekend is
    #[serde(rename = "ookGenoemd", skip_serializing_if = "Option::is_none")]
    pub ook_genoemd: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<models::CommercieleVestigingLinks>>,
}

impl NietCommercieleVestiging {
    /// De naam waaronder een niet commerciele vestiging bekend is
    pub fn new(vestigingsnummer: String) -> NietCommercieleVestiging {
        NietCommercieleVestiging {
            vestigingsnummer,
            naam: None,
            ook_genoemd: None,
            links: None,
        }
    }
}
