/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::naamgeving::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Vestiging {
    CommercieleVestiging(Box<models::CommercieleVestiging>),
    NietCommercieleVestiging(Box<models::NietCommercieleVestiging>),
}

impl Default for Vestiging {
    fn default() -> Self {
        Self::CommercieleVestiging(Default::default())
    }
}
