/*
 * API Vestigingsprofiel
 *
 * Documentatie voor API Vestigingsprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::vestigingsprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Adres {
    /// Correspondentieadres en/of bezoekadres
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Indicatie of het adres is afgeschermd
    #[serde(rename = "indAfgeschermd", skip_serializing_if = "Option::is_none")]
    pub ind_afgeschermd: Option<String>,
    #[serde(rename = "volledigAdres", skip_serializing_if = "Option::is_none")]
    pub volledig_adres: Option<String>,
    #[serde(rename = "straatnaam", skip_serializing_if = "Option::is_none")]
    pub straatnaam: Option<String>,
    #[serde(rename = "huisnummer", skip_serializing_if = "Option::is_none")]
    pub huisnummer: Option<i32>,
    #[serde(rename = "huisletter", skip_serializing_if = "Option::is_none")]
    pub huisletter: Option<String>,
    #[serde(
        rename = "huisnummerToevoeging",
        skip_serializing_if = "Option::is_none"
    )]
    pub huisnummer_toevoeging: Option<String>,
    #[serde(rename = "toevoegingAdres", skip_serializing_if = "Option::is_none")]
    pub toevoeging_adres: Option<String>,
    #[serde(rename = "postcode", skip_serializing_if = "Option::is_none")]
    pub postcode: Option<String>,
    #[serde(rename = "postbusnummer", skip_serializing_if = "Option::is_none")]
    pub postbusnummer: Option<i32>,
    #[serde(rename = "plaats", skip_serializing_if = "Option::is_none")]
    pub plaats: Option<String>,
    #[serde(rename = "straatHuisnummer", skip_serializing_if = "Option::is_none")]
    pub straat_huisnummer: Option<String>,
    #[serde(rename = "postcodeWoonplaats", skip_serializing_if = "Option::is_none")]
    pub postcode_woonplaats: Option<String>,
    #[serde(rename = "regio", skip_serializing_if = "Option::is_none")]
    pub regio: Option<String>,
    #[serde(rename = "land", skip_serializing_if = "Option::is_none")]
    pub land: Option<String>,
    #[serde(rename = "geoData", skip_serializing_if = "Option::is_none")]
    pub geo_data: Option<Box<models::GeoData>>,
}

impl Adres {
    pub fn new() -> Adres {
        Adres {
            r#type: None,
            ind_afgeschermd: None,
            volledig_adres: None,
            straatnaam: None,
            huisnummer: None,
            huisletter: None,
            huisnummer_toevoeging: None,
            toevoeging_adres: None,
            postcode: None,
            postbusnummer: None,
            plaats: None,
            straat_huisnummer: None,
            postcode_woonplaats: None,
            regio: None,
            land: None,
            geo_data: None,
        }
    }
}
