/*
 * API Vestigingsprofiel
 *
 * Documentatie voor API Vestigingsprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::vestigingsprofiel::models;
use serde::{Deserialize, Serialize};

/// GeoData : Basisregistratie Adressen en Gebouwen gegevens uit het kadaster
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeoData {
    /// Unieke BAG id
    #[serde(
        rename = "addresseerbaarObjectId",
        skip_serializing_if = "Option::is_none"
    )]
    pub addresseerbaar_object_id: Option<String>,
    /// Unieke BAG nummeraanduiding id
    #[serde(rename = "nummerAanduidingId", skip_serializing_if = "Option::is_none")]
    pub nummer_aanduiding_id: Option<String>,
    /// Lengtegraad
    #[serde(rename = "gpsLatitude", skip_serializing_if = "Option::is_none")]
    pub gps_latitude: Option<f64>,
    /// Breedtegraad
    #[serde(rename = "gpsLongitude", skip_serializing_if = "Option::is_none")]
    pub gps_longitude: Option<f64>,
    /// Rijksdriehoek X-coördinaat
    #[serde(rename = "rijksdriehoekX", skip_serializing_if = "Option::is_none")]
    pub rijksdriehoek_x: Option<f64>,
    /// Rijksdriehoek Y-coördinaat
    #[serde(rename = "rijksdriehoekY", skip_serializing_if = "Option::is_none")]
    pub rijksdriehoek_y: Option<f64>,
    /// Rijksdriehoek Z-coördinaat
    #[serde(rename = "rijksdriehoekZ", skip_serializing_if = "Option::is_none")]
    pub rijksdriehoek_z: Option<f64>,
}

impl GeoData {
    /// Basisregistratie Adressen en Gebouwen gegevens uit het kadaster
    pub fn new() -> GeoData {
        GeoData {
            addresseerbaar_object_id: None,
            nummer_aanduiding_id: None,
            gps_latitude: None,
            gps_longitude: None,
            rijksdriehoek_x: None,
            rijksdriehoek_y: None,
            rijksdriehoek_z: None,
        }
    }
}
