/*
 * API Vestigingsprofiel
 *
 * Documentatie voor API Vestigingsprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::vestigingsprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaterieleRegistratie {
    /// Startdatum onderneming. Voor API Vestigingsprofiel verwijst datumAanvang naar de startdatum van de vestiging en niet de onderneming.
    #[serde(rename = "datumAanvang", skip_serializing_if = "Option::is_none")]
    pub datum_aanvang: Option<String>,
    /// Einddatum onderneming. Voor API Vestigingsprofiel verwijst datumAanvang naar de einddatum van de vestiging en niet de onderneming.
    #[serde(rename = "datumEinde", skip_serializing_if = "Option::is_none")]
    pub datum_einde: Option<String>,
}

impl MaterieleRegistratie {
    pub fn new() -> MaterieleRegistratie {
        MaterieleRegistratie {
            datum_aanvang: None,
            datum_einde: None,
        }
    }
}
