/*
 * API Vestigingsprofiel
 *
 * Documentatie voor API Vestigingsprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::vestigingsprofiel::models;
use serde::{Deserialize, Serialize};

/// SbiActiviteit : Code beschrijving van SBI activiteiten conform SBI 2008 (Standard Industrial Classification). Er wordt geen maximering toegepast in de resultaten. Zie ook KVK.nl/sbi
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SbiActiviteit {
    #[serde(rename = "sbiCode", skip_serializing_if = "Option::is_none")]
    pub sbi_code: Option<String>,
    #[serde(rename = "sbiOmschrijving", skip_serializing_if = "Option::is_none")]
    pub sbi_omschrijving: Option<String>,
    #[serde(rename = "indHoofdactiviteit", skip_serializing_if = "Option::is_none")]
    pub ind_hoofdactiviteit: Option<String>,
}

impl SbiActiviteit {
    /// Code beschrijving van SBI activiteiten conform SBI 2008 (Standard Industrial Classification). Er wordt geen maximering toegepast in de resultaten. Zie ook KVK.nl/sbi
    pub fn new() -> SbiActiviteit {
        SbiActiviteit {
            sbi_code: None,
            sbi_omschrijving: None,
            ind_hoofdactiviteit: None,
        }
    }
}
