/*
 * API Vestigingsprofiel
 *
 * Documentatie voor API Vestigingsprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::vestigingsprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vestiging {
    /// Vestigingsnummer: uniek nummer dat bestaat uit 12 cijfers
    #[serde(rename = "vestigingsnummer", skip_serializing_if = "Option::is_none")]
    pub vestigingsnummer: Option<String>,
    /// Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers
    #[serde(rename = "kvkNummer", skip_serializing_if = "Option::is_none")]
    pub kvk_nummer: Option<String>,
    /// Rechtspersonen Samenwerkingsverbanden Informatie Nummer (dit outputveld wordt niet vermeld in de EmbeddedCointainer van hoofdvestiging).
    #[serde(rename = "rsin", skip_serializing_if = "Option::is_none")]
    pub rsin: Option<String>,
    /// Hiermee geeft de onderneming aan geen ongevraagde reclame per post of verkoop aan de deur te willen ontvangen
    #[serde(rename = "indNonMailing", skip_serializing_if = "Option::is_none")]
    pub ind_non_mailing: Option<String>,
    /// Registratiedatum onderneming in HR
    #[serde(
        rename = "formeleRegistratiedatum",
        skip_serializing_if = "Option::is_none"
    )]
    pub formele_registratiedatum: Option<String>,
    #[serde(
        rename = "materieleRegistratie",
        skip_serializing_if = "Option::is_none"
    )]
    pub materiele_registratie: Option<Box<models::MaterieleRegistratie>>,
    /// De naam van de vestiging wanneer er statuten geregistreerd zijn.
    #[serde(rename = "statutaireNaam", skip_serializing_if = "Option::is_none")]
    pub statutaire_naam: Option<String>,
    /// De naam waaronder een onderneming of vestiging handelt
    #[serde(rename = "eersteHandelsnaam", skip_serializing_if = "Option::is_none")]
    pub eerste_handelsnaam: Option<String>,
    /// Hoofdvestiging (Ja/Nee)
    #[serde(rename = "indHoofdvestiging", skip_serializing_if = "Option::is_none")]
    pub ind_hoofdvestiging: Option<String>,
    /// Commerciele vestiging  (Ja/Nee)
    #[serde(
        rename = "indCommercieleVestiging",
        skip_serializing_if = "Option::is_none"
    )]
    pub ind_commerciele_vestiging: Option<String>,
    /// Aantal voltijd werkzame personen
    #[serde(
        rename = "voltijdWerkzamePersonen",
        skip_serializing_if = "Option::is_none"
    )]
    pub voltijd_werkzame_personen: Option<i32>,
    /// Totaal aantal werkzame personen
    #[serde(
        rename = "totaalWerkzamePersonen",
        skip_serializing_if = "Option::is_none"
    )]
    pub totaal_werkzame_personen: Option<i32>,
    /// Aantal deeltijd werkzame personen
    #[serde(
        rename = "deeltijdWerkzamePersonen",
        skip_serializing_if = "Option::is_none"
    )]
    pub deeltijd_werkzame_personen: Option<i32>,
    /// Alle namen waaronder een vestiging handelt (op volgorde van registreren). Dit outputveld wordt niet vermeld in de EmbeddedCointainer van hoofdvestiging.
    #[serde(rename = "handelsnamen", skip_serializing_if = "Option::is_none")]
    pub handelsnamen: Option<Vec<models::Handelsnaam>>,
    #[serde(rename = "adressen", skip_serializing_if = "Option::is_none")]
    pub adressen: Option<Vec<models::Adres>>,
    #[serde(rename = "websites", skip_serializing_if = "Option::is_none")]
    pub websites: Option<Vec<String>>,
    /// Code beschrijving van SBI activiteiten conform SBI 2008 (Standard Industrial Classification). Er wordt geen maximering toegepast in de resultaten. Zie ook KVK.nl/sbi
    #[serde(rename = "sbiActiviteiten", skip_serializing_if = "Option::is_none")]
    pub sbi_activiteiten: Option<Vec<models::SbiActiviteit>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::LinksInner>>,
}

impl Vestiging {
    pub fn new() -> Vestiging {
        Vestiging {
            vestigingsnummer: None,
            kvk_nummer: None,
            rsin: None,
            ind_non_mailing: None,
            formele_registratiedatum: None,
            materiele_registratie: None,
            statutaire_naam: None,
            eerste_handelsnaam: None,
            ind_hoofdvestiging: None,
            ind_commerciele_vestiging: None,
            voltijd_werkzame_personen: None,
            totaal_werkzame_personen: None,
            deeltijd_werkzame_personen: None,
            handelsnamen: None,
            adressen: None,
            websites: None,
            sbi_activiteiten: None,
            links: None,
        }
    }
}
