/*
 * API Open Data Jaarrekeningen
 *
 * Open Data jaarrekeningen opvragen van een specifieke organisatie
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::open_data_jaarrekeningen::apis::ContentType;
use crate::open_data_jaarrekeningen::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait OpendataJaarrekeningenApi: Send + Sync {
    /// GET /api/v1/hvds/jaarrekeningen/kvknummer/{kvkNummer}
    ///
    ///
    async fn open_data_jaarrekeningen_bij_kvk_nummer(
        &self,
        params: OpenDataJaarrekeningenBijKvkNummerParams,
    ) -> Result<models::Opendata, Error<OpenDataJaarrekeningenBijKvkNummerError>>;
}

pub struct OpendataJaarrekeningenApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl OpendataJaarrekeningenApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`OpendataJaarrekeningenApi::open_data_jaarrekeningen_bij_kvk_nummer`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct OpenDataJaarrekeningenBijKvkNummerParams {
    /// __Nederlands Kamer van Koophandel nummer__: bestaat uit 8 cijfers
    pub kvk_nummer: String,
}

#[async_trait]
impl OpendataJaarrekeningenApi for OpendataJaarrekeningenApiClient {
    async fn open_data_jaarrekeningen_bij_kvk_nummer(
        &self,
        params: OpenDataJaarrekeningenBijKvkNummerParams,
    ) -> Result<models::Opendata, Error<OpenDataJaarrekeningenBijKvkNummerError>> {
        let OpenDataJaarrekeningenBijKvkNummerParams { kvk_nummer } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/v1/hvds/jaarrekeningen/kvknummer/{kvkNummer}",
            local_var_configuration.base_path,
            kvkNummer = crate::open_data_jaarrekeningen::apis::urlencode(kvk_nummer)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Opendata`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Opendata`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<OpenDataJaarrekeningenBijKvkNummerError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`OpendataJaarrekeningenApi::open_data_jaarrekeningen_bij_kvk_nummer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OpenDataJaarrekeningenBijKvkNummerError {
    Status404(models::Error),
    UnknownValue(serde_json::Value),
}
