/*
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::basisprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Basisprofiel {
    /// Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers
    #[serde(rename = "kvkNummer", skip_serializing_if = "Option::is_none")]
    pub kvk_nummer: Option<String>,
    /// Hiermee geeft de onderneming aan geen ongevraagde reclame per post of verkoop aan de deur te willen ontvangen
    #[serde(rename = "indNonMailing", skip_serializing_if = "Option::is_none")]
    pub ind_non_mailing: Option<String>,
    /// Naam onder Maatschappelijke Activiteit
    #[serde(rename = "naam", skip_serializing_if = "Option::is_none")]
    pub naam: Option<String>,
    /// Registratiedatum onderneming in HR
    #[serde(
        rename = "formeleRegistratiedatum",
        skip_serializing_if = "Option::is_none"
    )]
    pub formele_registratiedatum: Option<String>,
    #[serde(
        rename = "materieleRegistratie",
        skip_serializing_if = "Option::is_none"
    )]
    pub materiele_registratie: Option<Box<models::MaterieleRegistratie>>,
    /// Totaal aantal werkzame personen
    #[serde(
        rename = "totaalWerkzamePersonen",
        skip_serializing_if = "Option::is_none"
    )]
    pub totaal_werkzame_personen: Option<i32>,
    /// De naam van de onderneming wanneer er statuten geregistreerd zijn.
    #[serde(rename = "statutaireNaam", skip_serializing_if = "Option::is_none")]
    pub statutaire_naam: Option<String>,
    /// Alle namen waaronder een onderneming of vestiging handelt (op volgorde van registreren)
    #[serde(rename = "handelsnamen", skip_serializing_if = "Option::is_none")]
    pub handelsnamen: Option<Vec<models::Handelsnaam>>,
    /// Code beschrijving van SBI activiteiten conform SBI 2008 (Standard Industrial Classification). Er wordt geen maximering toegepast in de resultaten. Zie ook KVK.nl/sbi
    #[serde(rename = "sbiActiviteiten", skip_serializing_if = "Option::is_none")]
    pub sbi_activiteiten: Option<Vec<models::SbiActiviteit>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::LinksInner>>,
    #[serde(rename = "_embedded", skip_serializing_if = "Option::is_none")]
    pub _embedded: Option<Box<models::EmbeddedContainer>>,
}

impl Basisprofiel {
    pub fn new() -> Basisprofiel {
        Basisprofiel {
            kvk_nummer: None,
            ind_non_mailing: None,
            naam: None,
            formele_registratiedatum: None,
            materiele_registratie: None,
            totaal_werkzame_personen: None,
            statutaire_naam: None,
            handelsnamen: None,
            sbi_activiteiten: None,
            links: None,
            _embedded: None,
        }
    }
}
