/*
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::basisprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Eigenaar {
    /// Rechtspersonen Samenwerkingsverbanden Informatie Nummer
    #[serde(rename = "rsin", skip_serializing_if = "Option::is_none")]
    pub rsin: Option<String>,
    #[serde(rename = "rechtsvorm", skip_serializing_if = "Option::is_none")]
    pub rechtsvorm: Option<String>,
    #[serde(
        rename = "uitgebreideRechtsvorm",
        skip_serializing_if = "Option::is_none"
    )]
    pub uitgebreide_rechtsvorm: Option<String>,
    #[serde(rename = "adressen", skip_serializing_if = "Option::is_none")]
    pub adressen: Option<Vec<models::Adres>>,
    #[serde(rename = "websites", skip_serializing_if = "Option::is_none")]
    pub websites: Option<Vec<String>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::LinksInner>>,
}

impl Eigenaar {
    pub fn new() -> Eigenaar {
        Eigenaar {
            rsin: None,
            rechtsvorm: None,
            uitgebreide_rechtsvorm: None,
            adressen: None,
            websites: None,
            links: None,
        }
    }
}
