/*
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::basisprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddedContainer {
    #[serde(rename = "hoofdvestiging", skip_serializing_if = "Option::is_none")]
    pub hoofdvestiging: Option<Box<models::Vestiging>>,
    #[serde(rename = "eigenaar", skip_serializing_if = "Option::is_none")]
    pub eigenaar: Option<Box<models::Eigenaar>>,
}

impl EmbeddedContainer {
    pub fn new() -> EmbeddedContainer {
        EmbeddedContainer {
            hoofdvestiging: None,
            eigenaar: None,
        }
    }
}
