/*
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::basisprofiel::models;
use serde::{Deserialize, Serialize};

/// Handelsnaam : Alle namen waaronder een vestiging handelt (op volgorde van registreren). Dit outputveld wordt niet vermeld in de EmbeddedCointainer van hoofdvestiging.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Handelsnaam {
    #[serde(rename = "naam", skip_serializing_if = "Option::is_none")]
    pub naam: Option<String>,
    #[serde(rename = "volgorde", skip_serializing_if = "Option::is_none")]
    pub volgorde: Option<i32>,
}

impl Handelsnaam {
    /// Alle namen waaronder een vestiging handelt (op volgorde van registreren). Dit outputveld wordt niet vermeld in de EmbeddedCointainer van hoofdvestiging.
    pub fn new() -> Handelsnaam {
        Handelsnaam {
            naam: None,
            volgorde: None,
        }
    }
}
