/*
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::basisprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaterieleRegistratie {
    /// Startdatum onderneming
    #[serde(rename = "datumAanvang", skip_serializing_if = "Option::is_none")]
    pub datum_aanvang: Option<String>,
    /// Einddatum onderneming
    #[serde(rename = "datumEinde", skip_serializing_if = "Option::is_none")]
    pub datum_einde: Option<String>,
}

impl MaterieleRegistratie {
    pub fn new() -> MaterieleRegistratie {
        MaterieleRegistratie {
            datum_aanvang: None,
            datum_einde: None,
        }
    }
}
