/*
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::basisprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VestigingBasis {
    /// Vestigingsnummer: uniek nummer dat bestaat uit 12 cijfers
    #[serde(rename = "vestigingsnummer", skip_serializing_if = "Option::is_none")]
    pub vestigingsnummer: Option<String>,
    /// Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers
    #[serde(rename = "kvkNummer", skip_serializing_if = "Option::is_none")]
    pub kvk_nummer: Option<String>,
    /// De naam waaronder een onderneming of vestiging handelt
    #[serde(rename = "eersteHandelsnaam", skip_serializing_if = "Option::is_none")]
    pub eerste_handelsnaam: Option<String>,
    /// Hoofdvestiging (Ja/Nee)
    #[serde(rename = "indHoofdvestiging", skip_serializing_if = "Option::is_none")]
    pub ind_hoofdvestiging: Option<String>,
    /// Indicatie of het adres is afgeschermd
    #[serde(
        rename = "indAdresAfgeschermd",
        skip_serializing_if = "Option::is_none"
    )]
    pub ind_adres_afgeschermd: Option<String>,
    /// Commerciele vestiging  (Ja/Nee)
    #[serde(
        rename = "indCommercieleVestiging",
        skip_serializing_if = "Option::is_none"
    )]
    pub ind_commerciele_vestiging: Option<String>,
    #[serde(rename = "volledigAdres", skip_serializing_if = "Option::is_none")]
    pub volledig_adres: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::LinksInner>>,
}

impl VestigingBasis {
    pub fn new() -> VestigingBasis {
        VestigingBasis {
            vestigingsnummer: None,
            kvk_nummer: None,
            eerste_handelsnaam: None,
            ind_hoofdvestiging: None,
            ind_adres_afgeschermd: None,
            ind_commerciele_vestiging: None,
            volledig_adres: None,
            links: None,
        }
    }
}
