/*
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::basisprofiel::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VestigingList {
    /// Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers
    #[serde(rename = "kvkNummer", skip_serializing_if = "Option::is_none")]
    pub kvk_nummer: Option<String>,
    #[serde(
        rename = "aantalCommercieleVestigingen",
        skip_serializing_if = "Option::is_none"
    )]
    pub aantal_commerciele_vestigingen: Option<i64>,
    #[serde(
        rename = "aantalNietCommercieleVestigingen",
        skip_serializing_if = "Option::is_none"
    )]
    pub aantal_niet_commerciele_vestigingen: Option<i64>,
    #[serde(
        rename = "totaalAantalVestigingen",
        skip_serializing_if = "Option::is_none"
    )]
    pub totaal_aantal_vestigingen: Option<i64>,
    #[serde(rename = "vestigingen", skip_serializing_if = "Option::is_none")]
    pub vestigingen: Option<Vec<models::VestigingBasis>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::LinksInner>>,
}

impl VestigingList {
    pub fn new() -> VestigingList {
        VestigingList {
            kvk_nummer: None,
            aantal_commerciele_vestigingen: None,
            aantal_niet_commerciele_vestigingen: None,
            totaal_aantal_vestigingen: None,
            vestigingen: None,
            links: None,
        }
    }
}
