/*
 * API Open Data Jaarrekeningen
 *
 * Open Data jaarrekeningen opvragen van een specifieke organisatie
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::open_data_jaarrekeningen::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "melding", skip_serializing_if = "Option::is_none")]
    pub melding: Option<Vec<models::Melding>>,
}

impl Error {
    pub fn new() -> Error {
        Error { melding: None }
    }
}
