/*
 * API Open Data Jaarrekeningen
 *
 * Open Data jaarrekeningen opvragen van een specifieke organisatie
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::open_data_jaarrekeningen::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Melding {
    /// Foutcode
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Omschrijving van de foutmelding
    #[serde(rename = "omschrijving", skip_serializing_if = "Option::is_none")]
    pub omschrijving: Option<String>,
}

impl Melding {
    pub fn new() -> Melding {
        Melding {
            code: None,
            omschrijving: None,
        }
    }
}
