/*
 * API Open Data Jaarrekeningen
 *
 * Open Data jaarrekeningen opvragen van een specifieke organisatie
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::open_data_jaarrekeningen::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpendataField {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "opendataFields", skip_serializing_if = "Option::is_none")]
    pub opendata_fields: Option<Vec<models::OpendataField>>,
}

impl OpendataField {
    pub fn new() -> OpendataField {
        OpendataField {
            key: None,
            value: None,
            opendata_fields: None,
        }
    }
}
