/*
 * API Zoeken
 *
 * Documentatie voor API Zoeken.
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::zoeken::apis::ContentType;
use crate::zoeken::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait ZoekenApi: Send + Sync {
    /// GET /zoeken
    ///
    /// Er wordt max. 1000 resultaten getoond.
    async fn get_results(
        &self,
        params: GetResultsParams,
    ) -> Result<models::Resultaat, Error<GetResultsError>>;
}

pub struct ZoekenApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl ZoekenApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`ZoekenApi::get_results`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetResultsParams {
    /// Nederlands Kamer van Koophandel nummer dat bestaat uit 8 cijfers
    pub kvk_nummer: Option<String>,
    /// Rechtspersonen Samenwerkingsverbanden Informatie Nummer dat bestaat uit 9 cijfers
    pub rsin: Option<String>,
    /// Vestigingsnummer dat bestaat uit 12 cijfers
    pub vestigingsnummer: Option<String>,
    /// De naam waaronder een vestiging of rechtspersoon handelt
    pub naam: Option<String>,
    pub straatnaam: Option<String>,
    pub plaats: Option<String>,
    /// Mag alleen in combinatie met huisnummer of postbusnummer gezocht worden
    pub postcode: Option<String>,
    /// Mag alleen in combinatie met postcode gezocht worden
    pub huisnummer: Option<i32>,
    /// Optioneel. Alleen in combinatie met huisnummer
    pub huisletter: Option<String>,
    /// Mag alleen in combinatie met postcode gezocht worden
    pub postbusnummer: Option<i32>,
    /// Filter op type: hoofdvestiging, nevenvestiging en/of rechtspersoon
    pub r#type: Option<Vec<String>>,
    /// Inclusief inactieve registraties
    pub inclusief_inactieve_registraties: Option<bool>,
    /// Paginanummer, minimaal 1 en maximaal 1000
    pub pagina: Option<i32>,
    /// Kies het aantal resultaten per pagina, minimaal 1 en maximaal 100
    pub resultaten_per_pagina: Option<i8>,
}

#[async_trait]
impl ZoekenApi for ZoekenApiClient {
    /// Er wordt max. 1000 resultaten getoond.
    async fn get_results(
        &self,
        params: GetResultsParams,
    ) -> Result<models::Resultaat, Error<GetResultsError>> {
        let GetResultsParams {
            kvk_nummer,
            rsin,
            vestigingsnummer,
            naam,
            straatnaam,
            plaats,
            postcode,
            huisnummer,
            huisletter,
            postbusnummer,
            r#type,
            inclusief_inactieve_registraties,
            pagina,
            resultaten_per_pagina,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/zoeken", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = kvk_nummer {
            local_var_req_builder =
                local_var_req_builder.query(&[("kvkNummer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = rsin {
            local_var_req_builder =
                local_var_req_builder.query(&[("rsin", &param_value.to_string())]);
        }
        if let Some(ref param_value) = vestigingsnummer {
            local_var_req_builder =
                local_var_req_builder.query(&[("vestigingsnummer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = naam {
            local_var_req_builder =
                local_var_req_builder.query(&[("naam", &param_value.to_string())]);
        }
        if let Some(ref param_value) = straatnaam {
            local_var_req_builder =
                local_var_req_builder.query(&[("straatnaam", &param_value.to_string())]);
        }
        if let Some(ref param_value) = plaats {
            local_var_req_builder =
                local_var_req_builder.query(&[("plaats", &param_value.to_string())]);
        }
        if let Some(ref param_value) = postcode {
            local_var_req_builder =
                local_var_req_builder.query(&[("postcode", &param_value.to_string())]);
        }
        if let Some(ref param_value) = huisnummer {
            local_var_req_builder =
                local_var_req_builder.query(&[("huisnummer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = huisletter {
            local_var_req_builder =
                local_var_req_builder.query(&[("huisletter", &param_value.to_string())]);
        }
        if let Some(ref param_value) = postbusnummer {
            local_var_req_builder =
                local_var_req_builder.query(&[("postbusnummer", &param_value.to_string())]);
        }
        if let Some(ref param_value) = r#type {
            local_var_req_builder = match "multi" {
                "multi" => local_var_req_builder.query(
                    &param_value
                        .iter()
                        .map(|p| ("type".to_owned(), p.to_string()))
                        .collect::<Vec<(std::string::String, std::string::String)>>(),
                ),
                _ => local_var_req_builder.query(&[(
                    "type",
                    &param_value
                        .iter()
                        .map(|p| p.to_string())
                        .collect::<Vec<String>>()
                        .join(",")
                        .to_string(),
                )]),
            };
        }
        if let Some(ref param_value) = inclusief_inactieve_registraties {
            local_var_req_builder = local_var_req_builder
                .query(&[("inclusiefInactieveRegistraties", &param_value.to_string())]);
        }
        if let Some(ref param_value) = pagina {
            local_var_req_builder =
                local_var_req_builder.query(&[("pagina", &param_value.to_string())]);
        }
        if let Some(ref param_value) = resultaten_per_pagina {
            local_var_req_builder =
                local_var_req_builder.query(&[("resultatenPerPagina", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("apikey", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Resultaat`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Resultaat`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetResultsError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`ZoekenApi::get_results`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetResultsError {
    Status400(models::Error),
    Status401(models::Error),
    Status403(models::Error),
    Status404(models::Error),
    Status406(models::Error),
    Status500(models::Error),
    UnknownValue(serde_json::Value),
}
