/*
 * API Zoeken
 *
 * Documentatie voor API Zoeken.
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::zoeken::models;
use serde::{Deserialize, Serialize};

/// AdresType : Bezoekadres of postadres
/// Bezoekadres of postadres
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum AdresType {
    #[serde(rename = "bezoekadres")]
    #[default]
    Bezoekadres,
    #[serde(rename = "postadres")]
    Postadres,
}

impl std::fmt::Display for AdresType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bezoekadres => write!(f, "bezoekadres"),
            Self::Postadres => write!(f, "postadres"),
        }
    }
}
