/*
 * API Zoeken
 *
 * Documentatie voor API Zoeken.
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::zoeken::models;
use serde::{Deserialize, Serialize};

/// Adres : Binnenlands of buitenlands adres
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Adres {
    #[serde(rename = "binnenlandsAdres", skip_serializing_if = "Option::is_none")]
    pub binnenlands_adres: Option<Box<models::BinnenlandsAdres>>,
    #[serde(rename = "buitenlandsAdres", skip_serializing_if = "Option::is_none")]
    pub buitenlands_adres: Option<Box<models::BuitenlandsAdres>>,
}

impl Adres {
    /// Binnenlands of buitenlands adres
    pub fn new() -> Adres {
        Adres {
            binnenlands_adres: None,
            buitenlands_adres: None,
        }
    }
}
