/*
 * API Zoeken
 *
 * Documentatie voor API Zoeken.
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::zoeken::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BinnenlandsAdres {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::AdresType>,
    #[serde(rename = "straatnaam", skip_serializing_if = "Option::is_none")]
    pub straatnaam: Option<String>,
    #[serde(rename = "huisnummer", skip_serializing_if = "Option::is_none")]
    pub huisnummer: Option<i32>,
    #[serde(rename = "huisletter", skip_serializing_if = "Option::is_none")]
    pub huisletter: Option<String>,
    /// Postbusnummer wordt alleen getoond indien het een postadres betreft
    #[serde(rename = "postbusnummer", skip_serializing_if = "Option::is_none")]
    pub postbusnummer: Option<i32>,
    #[serde(rename = "postcode", skip_serializing_if = "Option::is_none")]
    pub postcode: Option<String>,
    #[serde(rename = "plaats", skip_serializing_if = "Option::is_none")]
    pub plaats: Option<String>,
}

impl BinnenlandsAdres {
    pub fn new() -> BinnenlandsAdres {
        BinnenlandsAdres {
            r#type: None,
            straatnaam: None,
            huisnummer: None,
            huisletter: None,
            postbusnummer: None,
            postcode: None,
            plaats: None,
        }
    }
}
