/*
 * API Zoeken
 *
 * Documentatie voor API Zoeken.
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::zoeken::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuitenlandsAdres {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::AdresType>,
    /// Het straat/huisnummer is een combinatie van de straat en huisnummer
    #[serde(rename = "straatHuisnummer", skip_serializing_if = "Option::is_none")]
    pub straat_huisnummer: Option<String>,
    /// De postcode/woonplaats is de combinatie van een eventuele postcode en woonplaats
    #[serde(rename = "postcodeWoonplaats", skip_serializing_if = "Option::is_none")]
    pub postcode_woonplaats: Option<String>,
    /// De naam van het land waar het adres bevindt
    #[serde(rename = "land", skip_serializing_if = "Option::is_none")]
    pub land: Option<String>,
}

impl BuitenlandsAdres {
    pub fn new() -> BuitenlandsAdres {
        BuitenlandsAdres {
            r#type: None,
            straat_huisnummer: None,
            postcode_woonplaats: None,
            land: None,
        }
    }
}
