/*
 * API Zoeken
 *
 * Documentatie voor API Zoeken.
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::zoeken::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Resultaat {
    /// Geeft aan op welke pagina je bent. Start vanaf pagina 1
    #[serde(rename = "pagina", skip_serializing_if = "Option::is_none")]
    pub pagina: Option<i32>,
    /// Geeft het aantal zoek resultaten per pagina weer
    #[serde(
        rename = "resultatenPerPagina",
        skip_serializing_if = "Option::is_none"
    )]
    pub resultaten_per_pagina: Option<i32>,
    /// Totaal aantal zoekresultaten gevonden. De API Zoeken toont max. 1000 resultaten.
    #[serde(rename = "totaal", skip_serializing_if = "Option::is_none")]
    pub totaal: Option<i32>,
    /// Link naar de vorige pagina indien beschikbaar
    #[serde(rename = "vorige", skip_serializing_if = "Option::is_none")]
    pub vorige: Option<String>,
    /// Link naar de volgende pagina indien beschikbaar
    #[serde(rename = "volgende", skip_serializing_if = "Option::is_none")]
    pub volgende: Option<String>,
    #[serde(rename = "resultaten", skip_serializing_if = "Option::is_none")]
    pub resultaten: Option<Vec<models::ResultaatItem>>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::LinksInner>>,
}

impl Resultaat {
    pub fn new() -> Resultaat {
        Resultaat {
            pagina: None,
            resultaten_per_pagina: None,
            totaal: None,
            vorige: None,
            volgende: None,
            resultaten: None,
            links: None,
        }
    }
}
