/*
 * API Zoeken
 *
 * Documentatie voor API Zoeken.
 *
 * The version of the OpenAPI document: 2.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::zoeken::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResultaatItem {
    /// Nederlands Kamer van Koophandel nummer dat bestaat uit 8 cijfers
    #[serde(rename = "kvkNummer", skip_serializing_if = "Option::is_none")]
    pub kvk_nummer: Option<String>,
    /// Rechtspersonen Samenwerkingsverbanden Informatie Nummer dat bestaat uit 9 cijfers
    #[serde(rename = "rsin", skip_serializing_if = "Option::is_none")]
    pub rsin: Option<String>,
    /// Vestigingsnummer dat bestaat uit 12 cijfers
    #[serde(rename = "vestigingsnummer", skip_serializing_if = "Option::is_none")]
    pub vestigingsnummer: Option<String>,
    /// De naam waaronder een vestiging of rechtspersoon handelt
    #[serde(rename = "naam", skip_serializing_if = "Option::is_none")]
    pub naam: Option<String>,
    #[serde(rename = "adres", skip_serializing_if = "Option::is_none")]
    pub adres: Option<Box<models::Adres>>,
    /// hoofdvestiging/nevenvestiging/rechtspersoon
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Indicatie of inschrijving actief is
    #[serde(rename = "actief", skip_serializing_if = "Option::is_none")]
    pub actief: Option<String>,
    /// Bevat de vervallen naam waaronder een vestiging of rechtspersoon heeft gehandeld
    #[serde(rename = "vervallenNaam", skip_serializing_if = "Option::is_none")]
    pub vervallen_naam: Option<String>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<models::LinksInner>>,
}

impl ResultaatItem {
    pub fn new() -> ResultaatItem {
        ResultaatItem {
            kvk_nummer: None,
            rsin: None,
            vestigingsnummer: None,
            naam: None,
            adres: None,
            r#type: None,
            actief: None,
            vervallen_naam: None,
            links: None,
        }
    }
}
