/*
 * API Basisprofiel
 *
 * Documentatie voor API Basisprofiel.
 *
 * The version of the OpenAPI document: 1.4.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::basisprofiel::apis::ContentType;
use crate::basisprofiel::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait BasisprofielApi: Send + Sync {
    /// GET /basisprofielen/{kvkNummer}
    ///
    ///
    async fn get_basisprofiel_by_kvk_nummer(
        &self,
        params: GetBasisprofielByKvkNummerParams,
    ) -> Result<models::Basisprofiel, Error<GetBasisprofielByKvkNummerError>>;

    /// GET /basisprofielen/{kvkNummer}/eigenaar
    ///
    ///
    async fn get_eigenaar(
        &self,
        params: GetEigenaarParams,
    ) -> Result<models::Eigenaar, Error<GetEigenaarError>>;

    /// GET /basisprofielen/{kvkNummer}/hoofdvestiging
    ///
    ///
    async fn get_hoofdvestiging(
        &self,
        params: GetHoofdvestigingParams,
    ) -> Result<models::Vestiging, Error<GetHoofdvestigingError>>;

    /// GET /basisprofielen/{kvkNummer}/vestigingen
    ///
    ///
    async fn get_vestigingen(
        &self,
        params: GetVestigingenParams,
    ) -> Result<models::VestigingList, Error<GetVestigingenError>>;
}

pub struct BasisprofielApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl BasisprofielApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`BasisprofielApi::get_basisprofiel_by_kvk_nummer`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetBasisprofielByKvkNummerParams {
    /// Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers
    pub kvk_nummer: String,
    pub geo_data: Option<bool>,
}

/// struct for passing parameters to the method [`BasisprofielApi::get_eigenaar`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetEigenaarParams {
    /// Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers
    pub kvk_nummer: String,
    pub geo_data: Option<bool>,
}

/// struct for passing parameters to the method [`BasisprofielApi::get_hoofdvestiging`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetHoofdvestigingParams {
    /// Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers
    pub kvk_nummer: String,
    pub geo_data: Option<bool>,
}

/// struct for passing parameters to the method [`BasisprofielApi::get_vestigingen`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetVestigingenParams {
    /// Nederlands Kamer van Koophandel nummer: bestaat uit 8 cijfers
    pub kvk_nummer: String,
}

#[async_trait]
impl BasisprofielApi for BasisprofielApiClient {
    async fn get_basisprofiel_by_kvk_nummer(
        &self,
        params: GetBasisprofielByKvkNummerParams,
    ) -> Result<models::Basisprofiel, Error<GetBasisprofielByKvkNummerError>> {
        let GetBasisprofielByKvkNummerParams {
            kvk_nummer,
            geo_data,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/basisprofielen/{kvkNummer}",
            local_var_configuration.base_path,
            kvkNummer = crate::basisprofiel::apis::urlencode(kvk_nummer)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = geo_data {
            local_var_req_builder =
                local_var_req_builder.query(&[("geoData", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("apikey", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Basisprofiel`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Basisprofiel`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetBasisprofielByKvkNummerError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_eigenaar(
        &self,
        params: GetEigenaarParams,
    ) -> Result<models::Eigenaar, Error<GetEigenaarError>> {
        let GetEigenaarParams {
            kvk_nummer,
            geo_data,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/basisprofielen/{kvkNummer}/eigenaar",
            local_var_configuration.base_path,
            kvkNummer = crate::basisprofiel::apis::urlencode(kvk_nummer)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = geo_data {
            local_var_req_builder =
                local_var_req_builder.query(&[("geoData", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("apikey", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Eigenaar`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Eigenaar`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetEigenaarError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_hoofdvestiging(
        &self,
        params: GetHoofdvestigingParams,
    ) -> Result<models::Vestiging, Error<GetHoofdvestigingError>> {
        let GetHoofdvestigingParams {
            kvk_nummer,
            geo_data,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/basisprofielen/{kvkNummer}/hoofdvestiging",
            local_var_configuration.base_path,
            kvkNummer = crate::basisprofiel::apis::urlencode(kvk_nummer)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = geo_data {
            local_var_req_builder =
                local_var_req_builder.query(&[("geoData", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("apikey", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Vestiging`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Vestiging`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetHoofdvestigingError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_vestigingen(
        &self,
        params: GetVestigingenParams,
    ) -> Result<models::VestigingList, Error<GetVestigingenError>> {
        let GetVestigingenParams { kvk_nummer } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/basisprofielen/{kvkNummer}/vestigingen",
            local_var_configuration.base_path,
            kvkNummer = crate::basisprofiel::apis::urlencode(kvk_nummer)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("apikey", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::VestigingList`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::VestigingList`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetVestigingenError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`BasisprofielApi::get_basisprofiel_by_kvk_nummer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBasisprofielByKvkNummerError {
    Status400(models::Error),
    Status401(models::Error),
    Status403(models::Error),
    Status404(models::Error),
    Status406(models::Error),
    Status500(models::Error),
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`BasisprofielApi::get_eigenaar`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEigenaarError {
    Status400(models::Error),
    Status401(models::Error),
    Status403(models::Error),
    Status404(models::Error),
    Status406(models::Error),
    Status500(models::Error),
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`BasisprofielApi::get_hoofdvestiging`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetHoofdvestigingError {
    Status400(models::Error),
    Status401(models::Error),
    Status403(models::Error),
    Status404(models::Error),
    Status406(models::Error),
    Status500(models::Error),
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`BasisprofielApi::get_vestigingen`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetVestigingenError {
    Status400(models::Error),
    Status401(models::Error),
    Status403(models::Error),
    Status404(models::Error),
    Status406(models::Error),
    Status500(models::Error),
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}
