/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbonnementJson {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "contract")]
    pub contract: Box<models::ContractInfo>,
    #[serde(rename = "startDatum")]
    pub start_datum: String,
    #[serde(rename = "eindDatum", skip_serializing_if = "Option::is_none")]
    pub eind_datum: Option<String>,
    #[serde(rename = "actief")]
    pub actief: bool,
}

impl AbonnementJson {
    pub fn new(
        id: String,
        contract: models::ContractInfo,
        start_datum: String,
        actief: bool,
    ) -> AbonnementJson {
        AbonnementJson {
            id,
            contract: Box::new(contract),
            start_datum,
            eind_datum: None,
            actief,
        }
    }
}
