/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbonnementenJsonResponseType {
    #[serde(rename = "klantId")]
    pub klant_id: String,
    #[serde(rename = "abonnementen")]
    pub abonnementen: Vec<models::AbonnementJson>,
}

impl AbonnementenJsonResponseType {
    pub fn new(
        klant_id: String,
        abonnementen: Vec<models::AbonnementJson>,
    ) -> AbonnementenJsonResponseType {
        AbonnementenJsonResponseType {
            klant_id,
            abonnementen,
        }
    }
}
