/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActiviteitType {
    #[serde(rename = "isHoofdactiviteit", skip_serializing_if = "Option::is_none")]
    pub is_hoofdactiviteit: Option<bool>,
    #[serde(rename = "sbiCode")]
    pub sbi_code: String,
}

impl ActiviteitType {
    pub fn new(sbi_code: String) -> ActiviteitType {
        ActiviteitType {
            is_hoofdactiviteit: None,
            sbi_code,
        }
    }
}
