/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActiviteitenWijzigingItemType {
    #[serde(rename = "functie")]
    pub functie: Box<models::ActiviteitenWijzigingItemTypeFunctie>,
    #[serde(rename = "soortMutatie")]
    pub soort_mutatie: Box<models::ActiviteitenWijzigingItemTypeSoortMutatie>,
    /// Categories associated with the position change
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
}

impl ActiviteitenWijzigingItemType {
    pub fn new(
        functie: models::ActiviteitenWijzigingItemTypeFunctie,
        soort_mutatie: models::ActiviteitenWijzigingItemTypeSoortMutatie,
        categories: Vec<String>,
    ) -> ActiviteitenWijzigingItemType {
        ActiviteitenWijzigingItemType {
            functie: Box::new(functie),
            soort_mutatie: Box::new(soort_mutatie),
            categories,
        }
    }
}
