/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActiviteitenWijzigingItemTypeSoortMutatie {
    /// Code identifying the type of change
    #[serde(rename = "code")]
    pub code: String,
    /// Human-readable description of the change
    #[serde(rename = "omschrijving")]
    pub omschrijving: String,
}

impl ActiviteitenWijzigingItemTypeSoortMutatie {
    pub fn new(code: String, omschrijving: String) -> ActiviteitenWijzigingItemTypeSoortMutatie {
        ActiviteitenWijzigingItemTypeSoortMutatie { code, omschrijving }
    }
}
