/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdreswijzigingType {
    #[serde(rename = "vestigingsnummer")]
    pub vestigingsnummer: String,
    #[serde(rename = "betreft")]
    pub betreft: Box<models::EnumeratieType>,
    #[serde(rename = "aanleiding")]
    pub aanleiding: Box<models::EnumeratieType>,
}

impl AdreswijzigingType {
    pub fn new(
        vestigingsnummer: String,
        betreft: models::EnumeratieType,
        aanleiding: models::EnumeratieType,
    ) -> AdreswijzigingType {
        AdreswijzigingType {
            vestigingsnummer,
            betreft: Box::new(betreft),
            aanleiding: Box::new(aanleiding),
        }
    }
}
