/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BetrokkenVestigingType {
    #[serde(rename = "vestigingsnummers", skip_serializing_if = "Option::is_none")]
    pub vestigingsnummers: Option<Vec<String>>,
}

impl BetrokkenVestigingType {
    pub fn new() -> BetrokkenVestigingType {
        BetrokkenVestigingType {
            vestigingsnummers: None,
        }
    }
}
