/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BetrokkenVestigingenType {
    #[serde(rename = "vestigingsnummers")]
    pub vestigingsnummers: Vec<String>,
}

impl BetrokkenVestigingenType {
    pub fn new(vestigingsnummers: Vec<String>) -> BetrokkenVestigingenType {
        BetrokkenVestigingenType { vestigingsnummers }
    }
}
