/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractInfo {
    #[serde(rename = "id")]
    pub id: String,
}

impl ContractInfo {
    pub fn new(id: String) -> ContractInfo {
        ContractInfo { id }
    }
}
