/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EigenaarType {
    #[serde(rename = "natuurlijkPersoon", skip_serializing_if = "Option::is_none")]
    pub natuurlijk_persoon: Option<Box<models::NatuurlijkPersoonType>>,
    #[serde(rename = "rechtspersoon", skip_serializing_if = "Option::is_none")]
    pub rechtspersoon: Option<Box<models::RechtspersoonType>>,
}

impl EigenaarType {
    pub fn new() -> EigenaarType {
        EigenaarType {
            natuurlijk_persoon: None,
            rechtspersoon: None,
        }
    }
}
