/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnumeratieType1 {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "omschrijving")]
    pub omschrijving: String,
}

impl EnumeratieType1 {
    pub fn new(code: String, omschrijving: String) -> EnumeratieType1 {
        EnumeratieType1 { code, omschrijving }
    }
}
