/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FusieSplitsingType {
    #[serde(rename = "startdatum")]
    pub startdatum: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "rol")]
    pub rol: String,
    #[serde(rename = "betrokkenOndernemingen")]
    pub betrokken_ondernemingen: Box<models::BetrokkenOndernemingenType>,
}

impl FusieSplitsingType {
    pub fn new(
        startdatum: String,
        r#type: String,
        status: String,
        rol: String,
        betrokken_ondernemingen: models::BetrokkenOndernemingenType,
    ) -> FusieSplitsingType {
        FusieSplitsingType {
            startdatum,
            r#type,
            status,
            rol,
            betrokken_ondernemingen: Box::new(betrokken_ondernemingen),
        }
    }
}
