/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "signaalType")]
pub enum GetSignaalResponseTypeSignaal {
    #[serde(rename = "SignaalGewijzigdeInschrijving")]
    SignaalGewijzigdeInschrijving(Box<models::SignaalGewijzigdeInschrijvingSignalType>),
    #[serde(rename = "SignaalGewijzigdeVestiging")]
    SignaalGewijzigdeVestiging(Box<models::SignaalGewijzigdeVestigingSignalType>),
    #[serde(rename = "SignaalNieuweInschrijving")]
    SignaalNieuweInschrijving(Box<models::SignaalNieuweInschrijvingSignalType>),
    #[serde(rename = "SignaalBeeindiging_2025_01")]
    SignaalBeeindiging202501(Box<models::SignaalBeeindiging202501SignalType>),
    #[serde(rename = "SignaalRechtsvormwijziging_2025_01")]
    SignaalRechtsvormwijziging202501(Box<models::SignaalRechtsvormwijziging202501SignalType>),
    #[serde(rename = "SignaalVoortzettingEnOverdracht_2025_01")]
    SignaalVoortzettingEnOverdracht202501(
        Box<models::SignaalVoortzettingEnOverdracht202501SignalType>,
    ),
    #[serde(rename = "SignaalAdreswijziging_2025_01")]
    SignaalAdreswijziging202501(Box<models::SignaalAdreswijziging202501SignalType>),
    #[serde(rename = "SignaalNaamgeving_2025_01")]
    SignaalNaamgeving202501(Box<models::SignaalNaamgeving202501SignalType>),
    #[serde(rename = "SignaalFusieSplitsing_2025_01")]
    SignaalFusieSplitsing202501(Box<models::SignaalFusieSplitsing202501SignalType>),
    #[serde(rename = "SignaalActiviteitenWijziging202501SignalType")]
    SignaalActiviteitenWijziging202501SignalType(
        Box<models::SignaalActiviteitenWijziging202501SignalType>,
    ),
}

impl Default for GetSignaalResponseTypeSignaal {
    fn default() -> Self {
        Self::SignaalGewijzigdeInschrijving(Default::default())
    }
}
