/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSignaalResponseType {
    #[serde(rename = "signaal")]
    pub signaal: Box<models::GetSignaalResponseTypeSignaal>,
}

impl GetSignaalResponseType {
    pub fn new(signaal: models::GetSignaalResponseTypeSignaal) -> GetSignaalResponseType {
        GetSignaalResponseType {
            signaal: Box::new(signaal),
        }
    }
}
