/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GewijzigdeVestigingenType {
    #[serde(
        rename = "gewijzigdevestigingen",
        skip_serializing_if = "Option::is_none"
    )]
    pub gewijzigdevestigingen: Option<Vec<models::GewijzigdeVestigingType>>,
}

impl GewijzigdeVestigingenType {
    pub fn new() -> GewijzigdeVestigingenType {
        GewijzigdeVestigingenType {
            gewijzigdevestigingen: None,
        }
    }
}
