/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GewijzigdeVestigingType {
    #[serde(rename = "activiteiten")]
    pub activiteiten: bool,
    #[serde(rename = "adresgegevens")]
    pub adresgegevens: bool,
    #[serde(rename = "algemeen")]
    pub algemeen: bool,
    #[serde(rename = "gevolmachtigden")]
    pub gevolmachtigden: bool,
    #[serde(rename = "naamgeving")]
    pub naamgeving: bool,
    #[serde(rename = "vestigingsnummer")]
    pub vestigingsnummer: String,
}

impl GewijzigdeVestigingType {
    pub fn new(
        activiteiten: bool,
        adresgegevens: bool,
        algemeen: bool,
        gevolmachtigden: bool,
        naamgeving: bool,
        vestigingsnummer: String,
    ) -> GewijzigdeVestigingType {
        GewijzigdeVestigingType {
            activiteiten,
            adresgegevens,
            algemeen,
            gevolmachtigden,
            naamgeving,
            vestigingsnummer,
        }
    }
}
