/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GewijzigdeFunctionarissenType {
    #[serde(rename = "aansprakelijke")]
    pub aansprakelijke: bool,
    #[serde(rename = "bestuursfunctie")]
    pub bestuursfunctie: bool,
    #[serde(rename = "functionarisBijzondereRechtstoestand")]
    pub functionaris_bijzondere_rechtstoestand: bool,
    #[serde(rename = "gemachtigde")]
    pub gemachtigde: bool,
    #[serde(rename = "overigeFunctionaris")]
    pub overige_functionaris: bool,
    #[serde(rename = "publiekRechtelijkeFunctionaris")]
    pub publiek_rechtelijke_functionaris: bool,
}

impl GewijzigdeFunctionarissenType {
    pub fn new(
        aansprakelijke: bool,
        bestuursfunctie: bool,
        functionaris_bijzondere_rechtstoestand: bool,
        gemachtigde: bool,
        overige_functionaris: bool,
        publiek_rechtelijke_functionaris: bool,
    ) -> GewijzigdeFunctionarissenType {
        GewijzigdeFunctionarissenType {
            aansprakelijke,
            bestuursfunctie,
            functionaris_bijzondere_rechtstoestand,
            gemachtigde,
            overige_functionaris,
            publiek_rechtelijke_functionaris,
        }
    }
}
