/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GewijzigdeDeponeringType {
    #[serde(rename = "aansprakelijkheid")]
    pub aansprakelijkheid: bool,
    #[serde(rename = "depotId")]
    pub depot_id: String,
    #[serde(rename = "jaarstuk")]
    pub jaarstuk: bool,
    #[serde(rename = "overigeDeponering")]
    pub overige_deponering: bool,
}

impl GewijzigdeDeponeringType {
    pub fn new(
        aansprakelijkheid: bool,
        depot_id: String,
        jaarstuk: bool,
        overige_deponering: bool,
    ) -> GewijzigdeDeponeringType {
        GewijzigdeDeponeringType {
            aansprakelijkheid,
            depot_id,
            jaarstuk,
            overige_deponering,
        }
    }
}
