/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GewijzigdeDeponeringenType {
    #[serde(
        rename = "gewijzigdeDeponeringen",
        skip_serializing_if = "Option::is_none"
    )]
    pub gewijzigde_deponeringen: Option<Vec<models::GewijzigdeDeponeringType>>,
}

impl GewijzigdeDeponeringenType {
    pub fn new() -> GewijzigdeDeponeringenType {
        GewijzigdeDeponeringenType {
            gewijzigde_deponeringen: None,
        }
    }
}
