/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GewijzigdeGegevensType {
    #[serde(rename = "deponeringen")]
    pub deponeringen: Box<models::GewijzigdeDeponeringenType>,
    #[serde(rename = "eigenaar")]
    pub eigenaar: Box<models::GewijzigdeEigenaarType>,
    #[serde(rename = "functionarissen")]
    pub functionarissen: Box<models::GewijzigdeFunctionarissenType>,
    #[serde(rename = "maOnderneming")]
    pub ma_onderneming: Box<models::GewijzigdeMaOndernemingType>,
    #[serde(rename = "vestigingen")]
    pub vestigingen: Box<models::GewijzigdeVestigingenType>,
}

impl GewijzigdeGegevensType {
    pub fn new(
        deponeringen: models::GewijzigdeDeponeringenType,
        eigenaar: models::GewijzigdeEigenaarType,
        functionarissen: models::GewijzigdeFunctionarissenType,
        ma_onderneming: models::GewijzigdeMaOndernemingType,
        vestigingen: models::GewijzigdeVestigingenType,
    ) -> GewijzigdeGegevensType {
        GewijzigdeGegevensType {
            deponeringen: Box::new(deponeringen),
            eigenaar: Box::new(eigenaar),
            functionarissen: Box::new(functionarissen),
            ma_onderneming: Box::new(ma_onderneming),
            vestigingen: Box::new(vestigingen),
        }
    }
}
