/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GewijzigdeEigenaarType {
    #[serde(rename = "beperkingInRechtshandeling")]
    pub beperking_in_rechtshandeling: bool,
    #[serde(rename = "bijzondererechtstoestand")]
    pub bijzondererechtstoestand: bool,
    #[serde(rename = "buitenlandseVennootschap")]
    pub buitenlandse_vennootschap: bool,
    #[serde(rename = "eenmanszaak")]
    pub eenmanszaak: bool,
    #[serde(rename = "eenmanszaakMetMeerdereEigenaren")]
    pub eenmanszaak_met_meerdere_eigenaren: bool,
    #[serde(rename = "fusieEnSplitsing")]
    pub fusie_en_splitsing: bool,
    #[serde(rename = "ontbindingEnLiquidatie")]
    pub ontbinding_en_liquidatie: bool,
    #[serde(rename = "rechtspersoon")]
    pub rechtspersoon: bool,
    #[serde(rename = "rechtspersoonActiviteiten")]
    pub rechtspersoon_activiteiten: bool,
    #[serde(rename = "rechtspersoonAdresgegevens")]
    pub rechtspersoon_adresgegevens: bool,
    #[serde(rename = "rechtspersoonInOprichting")]
    pub rechtspersoon_in_oprichting: bool,
    #[serde(rename = "samenwerkingsverband")]
    pub samenwerkingsverband: bool,
}

impl GewijzigdeEigenaarType {
    pub fn new(
        beperking_in_rechtshandeling: bool,
        bijzondererechtstoestand: bool,
        buitenlandse_vennootschap: bool,
        eenmanszaak: bool,
        eenmanszaak_met_meerdere_eigenaren: bool,
        fusie_en_splitsing: bool,
        ontbinding_en_liquidatie: bool,
        rechtspersoon: bool,
        rechtspersoon_activiteiten: bool,
        rechtspersoon_adresgegevens: bool,
        rechtspersoon_in_oprichting: bool,
        samenwerkingsverband: bool,
    ) -> GewijzigdeEigenaarType {
        GewijzigdeEigenaarType {
            beperking_in_rechtshandeling,
            bijzondererechtstoestand,
            buitenlandse_vennootschap,
            eenmanszaak,
            eenmanszaak_met_meerdere_eigenaren,
            fusie_en_splitsing,
            ontbinding_en_liquidatie,
            rechtspersoon,
            rechtspersoon_activiteiten,
            rechtspersoon_adresgegevens,
            rechtspersoon_in_oprichting,
            samenwerkingsverband,
        }
    }
}
