/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HateoasLinks {
    /// Een array van HATEOAS links.
    #[serde(rename = "links")]
    pub links: Vec<models::HateoasLink>,
}

impl HateoasLinks {
    pub fn new(links: Vec<models::HateoasLink>) -> HateoasLinks {
        HateoasLinks { links }
    }
}
