/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocatieType {
    #[serde(rename = "afgeschermd")]
    pub afgeschermd: bool,
    #[serde(rename = "postcode", skip_serializing_if = "Option::is_none")]
    pub postcode: Option<Box<models::PostcodeType>>,
}

impl LocatieType {
    pub fn new(afgeschermd: bool) -> LocatieType {
        LocatieType {
            afgeschermd,
            postcode: None,
        }
    }
}
