/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaatschappelijkeActiviteitType {
    #[serde(rename = "heeftAlsEigenaar", skip_serializing_if = "Option::is_none")]
    pub heeft_als_eigenaar: Option<Box<models::EigenaarType>>,
    #[serde(rename = "kvkNummer")]
    pub kvk_nummer: String,
    #[serde(rename = "nonMailing")]
    pub non_mailing: bool,
    #[serde(
        rename = "totaalWerkzamePersonen",
        skip_serializing_if = "Option::is_none"
    )]
    pub totaal_werkzame_personen: Option<i32>,
    #[serde(rename = "wordtUitgeoefendIn", skip_serializing_if = "Option::is_none")]
    pub wordt_uitgeoefend_in: Option<Vec<models::VestigingType>>,
}

impl MaatschappelijkeActiviteitType {
    pub fn new(kvk_nummer: String, non_mailing: bool) -> MaatschappelijkeActiviteitType {
        MaatschappelijkeActiviteitType {
            heeft_als_eigenaar: None,
            kvk_nummer,
            non_mailing,
            totaal_werkzame_personen: None,
            wordt_uitgeoefend_in: None,
        }
    }
}
