/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NatuurlijkPersoonType {
    #[serde(rename = "persoonRechtsvorm", skip_serializing_if = "Option::is_none")]
    pub persoon_rechtsvorm: Option<String>,
}

impl NatuurlijkPersoonType {
    pub fn new() -> NatuurlijkPersoonType {
        NatuurlijkPersoonType {
            persoon_rechtsvorm: None,
        }
    }
}
