/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedSignalenHalJsonType {
    #[serde(rename = "pagina")]
    pub pagina: i32,
    #[serde(rename = "aantal")]
    pub aantal: i32,
    #[serde(rename = "totaal")]
    pub totaal: f64,
    #[serde(rename = "totaalPaginas")]
    pub totaal_paginas: i32,
    #[serde(rename = "signalen")]
    pub signalen: Vec<models::SignaalInfoHal>,
    #[serde(rename = "vorige", skip_serializing_if = "Option::is_none")]
    pub vorige: Option<String>,
    #[serde(rename = "volgende", skip_serializing_if = "Option::is_none")]
    pub volgende: Option<String>,
}

impl PagedSignalenHalJsonType {
    pub fn new(
        pagina: i32,
        aantal: i32,
        totaal: f64,
        totaal_paginas: i32,
        signalen: Vec<models::SignaalInfoHal>,
    ) -> PagedSignalenHalJsonType {
        PagedSignalenHalJsonType {
            pagina,
            aantal,
            totaal,
            totaal_paginas,
            signalen,
            vorige: None,
            volgende: None,
        }
    }
}
