/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginationInfo {
    #[serde(rename = "pagina")]
    pub pagina: i32,
    #[serde(rename = "aantal")]
    pub aantal: i32,
    #[serde(rename = "totaal")]
    pub totaal: f64,
    #[serde(rename = "totaalPaginas")]
    pub totaal_paginas: i32,
}

impl PaginationInfo {
    pub fn new(pagina: i32, aantal: i32, totaal: f64, totaal_paginas: i32) -> PaginationInfo {
        PaginationInfo {
            pagina,
            aantal,
            totaal,
            totaal_paginas,
        }
    }
}
