/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostcodeType {
    #[serde(rename = "cijfercombinatie")]
    pub cijfercombinatie: String,
    #[serde(rename = "lettercombinatie", skip_serializing_if = "Option::is_none")]
    pub lettercombinatie: Option<String>,
}

impl PostcodeType {
    pub fn new(cijfercombinatie: String) -> PostcodeType {
        PostcodeType {
            cijfercombinatie,
            lettercombinatie: None,
        }
    }
}
