/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

/// ProblemDetail : beschrijving van een fout die opgetreden is
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemDetail {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "status")]
    pub status: i32,
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ProblemDetail {
    /// beschrijving van een fout die opgetreden is
    pub fn new(r#type: String, status: i32) -> ProblemDetail {
        ProblemDetail {
            r#type,
            title: None,
            status,
            detail: None,
            instance: None,
            properties: None,
        }
    }
}
