/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RechtspersoonType {
    #[serde(rename = "activiteiten", skip_serializing_if = "Option::is_none")]
    pub activiteiten: Option<Vec<models::ActiviteitType>>,
    #[serde(rename = "bezoekadres", skip_serializing_if = "Option::is_none")]
    pub bezoekadres: Option<Box<models::LocatieType>>,
    #[serde(rename = "persoonRechtsvorm", skip_serializing_if = "Option::is_none")]
    pub persoon_rechtsvorm: Option<String>,
    #[serde(rename = "rsin", skip_serializing_if = "Option::is_none")]
    pub rsin: Option<String>,
}

impl RechtspersoonType {
    pub fn new() -> RechtspersoonType {
        RechtspersoonType {
            activiteiten: None,
            bezoekadres: None,
            persoon_rechtsvorm: None,
            rsin: None,
        }
    }
}
