/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignaalInfo {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "kvknummer")]
    pub kvknummer: String,
    #[serde(rename = "signaalType", skip_serializing_if = "Option::is_none")]
    pub signaal_type: Option<models::SignaalType>,
    #[serde(rename = "vestigingsnummer", skip_serializing_if = "Option::is_none")]
    pub vestigingsnummer: Option<String>,
}

impl SignaalInfo {
    pub fn new(id: String, timestamp: String, kvknummer: String) -> SignaalInfo {
        SignaalInfo {
            id,
            timestamp,
            kvknummer,
            signaal_type: None,
            vestigingsnummer: None,
        }
    }
}
