/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignaalNaamgeving202501SignalType {
    #[serde(rename = "berichtId")]
    pub bericht_id: String,
    #[serde(rename = "heeftBetrekkingOp")]
    pub heeft_betrekking_op: Box<models::MaatschappelijkeActiviteitType>,
    #[serde(rename = "registratieId")]
    pub registratie_id: String,
    #[serde(rename = "registratieTijdstip")]
    pub registratie_tijdstip: String,
    #[serde(rename = "signaalType")]
    pub signaal_type: models::SignaalType,
    #[serde(rename = "wijzigingNaam")]
    pub wijziging_naam: Box<models::WijzigingNaam>,
    #[serde(rename = "betrokkenVestigingen")]
    pub betrokken_vestigingen: Box<models::BetrokkenVestigingType>,
}

impl SignaalNaamgeving202501SignalType {
    pub fn new(
        bericht_id: String,
        heeft_betrekking_op: models::MaatschappelijkeActiviteitType,
        registratie_id: String,
        registratie_tijdstip: String,
        signaal_type: models::SignaalType,
        wijziging_naam: models::WijzigingNaam,
        betrokken_vestigingen: models::BetrokkenVestigingType,
    ) -> SignaalNaamgeving202501SignalType {
        SignaalNaamgeving202501SignalType {
            bericht_id,
            heeft_betrekking_op: Box::new(heeft_betrekking_op),
            registratie_id,
            registratie_tijdstip,
            signaal_type,
            wijziging_naam: Box::new(wijziging_naam),
            betrokken_vestigingen: Box::new(betrokken_vestigingen),
        }
    }
}
