/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignaalBeeindiging202501SignalType {
    #[serde(rename = "berichtId")]
    pub bericht_id: String,
    #[serde(rename = "heeftBetrekkingOp")]
    pub heeft_betrekking_op: Box<models::MaatschappelijkeActiviteitType>,
    #[serde(rename = "registratieId")]
    pub registratie_id: String,
    #[serde(rename = "registratieTijdstip")]
    pub registratie_tijdstip: String,
    #[serde(rename = "signaalType")]
    pub signaal_type: models::SignaalType,
    /// Een datum heeft een vast formaat: 8 posities, met als invulling jjjjmmdd (jaar-maand-dag), waarbij alleen cijfers zijn toegestaan.  Wanneer een gedeelte van de datum onbekend is, wordt dat gerepresenteerd door nullen.  De mogelijke waarden van datum zijn:jjjjmmdd volledige datum, jjjjmm00 dag onbekend, jjjj0000 maand onbekend, 00000000 datum onbekend, standaardwaarde
    #[serde(rename = "startdatum")]
    pub startdatum: String,
    #[serde(rename = "aanleiding")]
    pub aanleiding: Box<models::EnumeratieType>,
}

impl SignaalBeeindiging202501SignalType {
    pub fn new(
        bericht_id: String,
        heeft_betrekking_op: models::MaatschappelijkeActiviteitType,
        registratie_id: String,
        registratie_tijdstip: String,
        signaal_type: models::SignaalType,
        startdatum: String,
        aanleiding: models::EnumeratieType,
    ) -> SignaalBeeindiging202501SignalType {
        SignaalBeeindiging202501SignalType {
            bericht_id,
            heeft_betrekking_op: Box::new(heeft_betrekking_op),
            registratie_id,
            registratie_tijdstip,
            signaal_type,
            startdatum,
            aanleiding: Box::new(aanleiding),
        }
    }
}
