/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignaalNieuweInschrijvingType {
    #[serde(rename = "aanleiding")]
    pub aanleiding: Box<models::EnumeratieType1>,
    #[serde(rename = "kvkNummer", skip_serializing_if = "Option::is_none")]
    pub kvk_nummer: Option<String>,
    #[serde(rename = "startdatum")]
    pub startdatum: String,
}

impl SignaalNieuweInschrijvingType {
    pub fn new(
        aanleiding: models::EnumeratieType1,
        startdatum: String,
    ) -> SignaalNieuweInschrijvingType {
        SignaalNieuweInschrijvingType {
            aanleiding: Box::new(aanleiding),
            kvk_nummer: None,
            startdatum,
        }
    }
}
