/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum SignaalType {
    #[serde(rename = "SignaalGewijzigdeInschrijving")]
    #[default]
    SignaalGewijzigdeInschrijving,
    #[serde(rename = "SignaalNieuweInschrijving")]
    SignaalNieuweInschrijving,
    #[serde(rename = "SignaalGewijzigdeVestiging")]
    SignaalGewijzigdeVestiging,
    #[serde(rename = "SignaalBeeindiging_2025_01")]
    SignaalBeeindiging202501,
    #[serde(rename = "SignaalRechtsvormwijziging_2025_01")]
    SignaalRechtsvormwijziging202501,
    #[serde(rename = "SignaalVoortzettingEnOverdracht_2025_01")]
    SignaalVoortzettingEnOverdracht202501,
    #[serde(rename = "SignaalAdreswijziging_2025_01")]
    SignaalAdreswijziging202501,
    #[serde(rename = "SignaalNaamgeving_2025_01")]
    SignaalNaamgeving202501,
    #[serde(rename = "SignaalFusieSplitsing_2025_01")]
    SignaalFusieSplitsing202501,
    #[serde(rename = "SignaalActiviteitenWijziging_2025_01")]
    SignaalActiviteitenWijziging202501,
}

impl std::fmt::Display for SignaalType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SignaalGewijzigdeInschrijving => write!(f, "SignaalGewijzigdeInschrijving"),
            Self::SignaalNieuweInschrijving => write!(f, "SignaalNieuweInschrijving"),
            Self::SignaalGewijzigdeVestiging => write!(f, "SignaalGewijzigdeVestiging"),
            Self::SignaalBeeindiging202501 => write!(f, "SignaalBeeindiging_2025_01"),
            Self::SignaalRechtsvormwijziging202501 => {
                write!(f, "SignaalRechtsvormwijziging_2025_01")
            }
            Self::SignaalVoortzettingEnOverdracht202501 => {
                write!(f, "SignaalVoortzettingEnOverdracht_2025_01")
            }
            Self::SignaalAdreswijziging202501 => write!(f, "SignaalAdreswijziging_2025_01"),
            Self::SignaalNaamgeving202501 => write!(f, "SignaalNaamgeving_2025_01"),
            Self::SignaalFusieSplitsing202501 => write!(f, "SignaalFusieSplitsing_2025_01"),
            Self::SignaalActiviteitenWijziging202501 => {
                write!(f, "SignaalActiviteitenWijziging_2025_01")
            }
        }
    }
}
