/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VestigingType {
    #[serde(rename = "activiteiten", skip_serializing_if = "Option::is_none")]
    pub activiteiten: Option<Vec<models::ActiviteitType>>,
    #[serde(rename = "bezoekadres", skip_serializing_if = "Option::is_none")]
    pub bezoekadres: Option<Box<models::LocatieType>>,
    #[serde(rename = "isHoofdvestiging", skip_serializing_if = "Option::is_none")]
    pub is_hoofdvestiging: Option<bool>,
    #[serde(
        rename = "totaalWerkzamePersonen",
        skip_serializing_if = "Option::is_none"
    )]
    pub totaal_werkzame_personen: Option<i32>,
    #[serde(rename = "vestigingsnummer")]
    pub vestigingsnummer: String,
}

impl VestigingType {
    pub fn new(vestigingsnummer: String) -> VestigingType {
        VestigingType {
            activiteiten: None,
            bezoekadres: None,
            is_hoofdvestiging: None,
            totaal_werkzame_personen: None,
            vestigingsnummer,
        }
    }
}
