/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VestigingDetailsType {
    #[serde(rename = "gewijzigdeGegevens")]
    pub gewijzigde_gegevens: Box<models::GewijzigdeVestigingGegevensType>,
    #[serde(rename = "isCommercieel")]
    pub is_commercieel: bool,
    #[serde(rename = "isHoofdvestiging")]
    pub is_hoofdvestiging: bool,
    #[serde(rename = "vestigingsnummer")]
    pub vestigingsnummer: String,
}

impl VestigingDetailsType {
    pub fn new(
        gewijzigde_gegevens: models::GewijzigdeVestigingGegevensType,
        is_commercieel: bool,
        is_hoofdvestiging: bool,
        vestigingsnummer: String,
    ) -> VestigingDetailsType {
        VestigingDetailsType {
            gewijzigde_gegevens: Box::new(gewijzigde_gegevens),
            is_commercieel,
            is_hoofdvestiging,
            vestigingsnummer,
        }
    }
}
