/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoortzettingEnOverdrachtType {
    #[serde(rename = "betrokkenVestigingen")]
    pub betrokken_vestigingen: Box<models::BetrokkenVestigingenType>,
    #[serde(rename = "rolBijVoortzettingOverdracht")]
    pub rol_bij_voortzetting_overdracht: Box<models::EnumeratieType>,
    #[serde(rename = "kvkNummer")]
    pub kvk_nummer: String,
    #[serde(rename = "persoonRechtsvorm")]
    pub persoon_rechtsvorm: String,
}

impl VoortzettingEnOverdrachtType {
    pub fn new(
        betrokken_vestigingen: models::BetrokkenVestigingenType,
        rol_bij_voortzetting_overdracht: models::EnumeratieType,
        kvk_nummer: String,
        persoon_rechtsvorm: String,
    ) -> VoortzettingEnOverdrachtType {
        VoortzettingEnOverdrachtType {
            betrokken_vestigingen: Box::new(betrokken_vestigingen),
            rol_bij_voortzetting_overdracht: Box::new(rol_bij_voortzetting_overdracht),
            kvk_nummer,
            persoon_rechtsvorm,
        }
    }
}
