/*
 * HP Mutatie Service - Delivery
 *
 * mutatie service delivery
 *
 * The version of the OpenAPI document: 1.0.9
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::mutatieservice::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WijzigingNaam {
    #[serde(rename = "statutaireNaam")]
    pub statutaire_naam: String,
    #[serde(rename = "handelsNaam")]
    pub handels_naam: String,
}

impl WijzigingNaam {
    pub fn new(statutaire_naam: String, handels_naam: String) -> WijzigingNaam {
        WijzigingNaam {
            statutaire_naam,
            handels_naam,
        }
    }
}
