/*
 * Naamgeving API
 *
 * Naamgeving informatie opvragen van een specifiek bedrijf en/of vestiging
 *
 * The version of the OpenAPI document: 1.1.1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::naamgeving::apis::ContentType;
use crate::naamgeving::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait NaamgevingApi: Send + Sync {
    /// GET /naamgevingen/kvknummer/{kvkNummer}
    ///
    ///
    async fn naamgeving_bij_kvk_nummer(
        &self,
        params: NaamgevingBijKvkNummerParams,
    ) -> Result<models::Naamgeving, Error<NaamgevingBijKvkNummerError>>;
}

pub struct NaamgevingApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl NaamgevingApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`NaamgevingApi::naamgeving_bij_kvk_nummer`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct NaamgevingBijKvkNummerParams {
    /// __Nederlands Kamer van Koophandel nummer__: bestaat uit 8 cijfers
    pub kvk_nummer: String,
}

#[async_trait]
impl NaamgevingApi for NaamgevingApiClient {
    async fn naamgeving_bij_kvk_nummer(
        &self,
        params: NaamgevingBijKvkNummerParams,
    ) -> Result<models::Naamgeving, Error<NaamgevingBijKvkNummerError>> {
        let NaamgevingBijKvkNummerParams { kvk_nummer } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/naamgevingen/kvknummer/{kvkNummer}",
            local_var_configuration.base_path,
            kvkNummer = crate::naamgeving::apis::urlencode(kvk_nummer)
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("apikey", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Naamgeving`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Naamgeving`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<NaamgevingBijKvkNummerError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`NaamgevingApi::naamgeving_bij_kvk_nummer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NaamgevingBijKvkNummerError {
    Status400(models::Error),
    Status401(models::Error),
    Status403(models::Error),
    Status404(models::Error),
    Status406(models::Error),
    Status500(models::Error),
    DefaultResponse(models::Error),
    UnknownValue(serde_json::Value),
}
