/*
 * KVK Handelsregister Open Dataset Basis Bedrijfsgegevens
 *
 * Open Data basis bedrijfsgegevens opvragen van een specifieke organisatie
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::open_data_basis::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Activiteit {
    /// De SBI-code is een code (van maximaal 6 cijfers) voor de classificatie van activiteiten. De codering van de activiteit is conform de SBI classificatie bij CBS.
    #[serde(rename = "sbiCode", skip_serializing_if = "Option::is_none")]
    pub sbi_code: Option<String>,
    /// Geeft aan of een activiteit een hoofdactiviteit of nevenactiviteit is van de onderneming.
    #[serde(rename = "soortActiviteit", skip_serializing_if = "Option::is_none")]
    pub soort_activiteit: Option<SoortActiviteit>,
}

impl Activiteit {
    pub fn new() -> Activiteit {
        Activiteit {
            sbi_code: None,
            soort_activiteit: None,
        }
    }
}
/// Geeft aan of een activiteit een hoofdactiviteit of nevenactiviteit is van de onderneming.
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum SoortActiviteit {
    #[serde(rename = "Hoofdactiviteit")]
    #[default]
    Hoofdactiviteit,
    #[serde(rename = "Nevenactiviteit")]
    Nevenactiviteit,
}
