/*
 * KVK Handelsregister Open Dataset Basis Bedrijfsgegevens
 *
 * Open Data basis bedrijfsgegevens opvragen van een specifieke organisatie
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::open_data_basis::models;
use serde::{Deserialize, Serialize};

/// ActiefIndicatie : Indicator die aangeeft of de inschrijving actief of inactief is. Indicatoren:   * `J` - Actief   * `N` - Inactief
/// Indicator die aangeeft of de inschrijving actief of inactief is. Indicatoren:   * `J` - Actief   * `N` - Inactief
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum ActiefIndicatie {
    #[serde(rename = "J")]
    #[default]
    J,
    #[serde(rename = "N")]
    N,
}

impl std::fmt::Display for ActiefIndicatie {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::J => write!(f, "J"),
            Self::N => write!(f, "N"),
        }
    }
}
