/*
 * KVK Handelsregister Open Dataset Basis Bedrijfsgegevens
 *
 * Open Data basis bedrijfsgegevens opvragen van een specifieke organisatie
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::open_data_basis::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "fout", skip_serializing_if = "Option::is_none")]
    pub fout: Option<Vec<models::Fout>>,
}

impl Error {
    pub fn new() -> Error {
        Error { fout: None }
    }
}
