/*
 * KVK Handelsregister Open Dataset Basis Bedrijfsgegevens
 *
 * Open Data basis bedrijfsgegevens opvragen van een specifieke organisatie
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::open_data_basis::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenData {
    /// De datum waarop de activiteiten van een onderneming of rechtspersoon start of gestart is.
    #[serde(rename = "datumAanvang", skip_serializing_if = "Option::is_none")]
    pub datum_aanvang: Option<String>,
    #[serde(rename = "actief", skip_serializing_if = "Option::is_none")]
    pub actief: Option<models::ActiefIndicatie>,
    /// Het soort bijzondere rechtstoestand:   * `FAIL` - Faillissement   * `SSAN` - Schuldsanering   * `SURS` - Surseance van betaling
    #[serde(rename = "insolventieCode", skip_serializing_if = "Option::is_none")]
    pub insolventie_code: Option<InsolventieCode>,
    /// De rechtsvorm code van de organisatie.
    #[serde(rename = "rechtsvormCode", skip_serializing_if = "Option::is_none")]
    pub rechtsvorm_code: Option<String>,
    /// Het regiodeel van de postcode van het bezoekadres. Dit zijn de eerste twee cijfers van de postcode.
    #[serde(rename = "postcodeRegio", skip_serializing_if = "Option::is_none")]
    pub postcode_regio: Option<i32>,
    /// De verzameling van alle activiteiten van de organisatie.
    #[serde(rename = "activiteiten", skip_serializing_if = "Option::is_none")]
    pub activiteiten: Option<Vec<models::Activiteit>>,
    /// Lidstaat waar de organisatie gevestigd is.
    #[serde(rename = "lidstaat", skip_serializing_if = "Option::is_none")]
    pub lidstaat: Option<String>,
}

impl OpenData {
    pub fn new() -> OpenData {
        OpenData {
            datum_aanvang: None,
            actief: None,
            insolventie_code: None,
            rechtsvorm_code: None,
            postcode_regio: None,
            activiteiten: None,
            lidstaat: None,
        }
    }
}
/// Het soort bijzondere rechtstoestand:   * `FAIL` - Faillissement   * `SSAN` - Schuldsanering   * `SURS` - Surseance van betaling
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum InsolventieCode {
    #[serde(rename = "FAIL")]
    #[default]
    Fail,
    #[serde(rename = "SSAN")]
    Ssan,
    #[serde(rename = "SURS")]
    Surs,
}
